name: CI

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Install Clang
        uses: egor-tensin/setup-clang@v1

      - name: Run a multi-line script
        run: |
          for file in `find . -name '*.h' -or -name '*.cpp' -or -name '*.hpp'`
          do
            echo 'clang-tidy checking...' && clang-tidy $file
            echo 'clang-format checking...' && diff $file <(clang-format $file)
          done
